### ISSUE TITLE
Pseudo-Labels for ChangeIt dataset

### ISSUE THREAD

**Issue by MasaTate** [facebookresearch/VidOSC#2]
Hi, thank you for releasing your dataset and code.

Currently, I'm trying to reproduce your work on ChangeIt dataset.
Could you please release the VideoCLIP pseudo-labels for ChangeIt dataset?

I'm facing slow inference of VideoCLIP due to its batch size limitation (batch size is limited to 1).
If it is difficult to release the pseudo-labels, I would appreciate your advice on how to extract features quickly using VideoCLIP.

Thank you again for your support.

**Comment by ZhichaoWang6** [comment]
> VideoCLIP pseudo-labels for ChangeIt dataset

Hi, I have the same problem. If you have solved it, could you please provide me with a copy? Thank you very much.
