### ISSUE TITLE
Complete HowToChange Videos

### ISSUE THREAD

**Issue by ZhichaoWang6** [facebookresearch/VidOSC#3]
Hi, thank you for releasing your dataset and code.
Could you please release the complete HowToChange videos?
Thank you again for your support.

**Comment by zihuixue** [comment]
Hi @Wangzc-kimo,

Thank you for your interest in our work! Please fill out this [form](https://forms.gle/7gmf39H9BKB8Q3vFA) to access the complete HowToChange videos. After submitting the form, you'll receive an email with access details.
