### ISSUE TITLE
Features and  Pseudo-Labels of  Changeit Datasets

### ISSUE THREAD

**Issue by ZhichaoWang6** [facebookresearch/VidOSC#4]
Hi, thank you for releasing your dataset and code.
Could you please release the features and  pseudo-labels of  Changeit datasets?
Thank you again for your support.

**Comment by zihuixue** [comment]
Hi @Wangzc-kimo ,

Thank you for your interest in our work. Please see the files for the ChangeIt dataset [here](https://drive.google.com/drive/folders/1z9RQIp4X1lmRSRDZ93oHGoBCKw_hZGpA?usp=share_link).
