### ISSUE TITLE
Train Annotations files of Changeit dataset

### ISSUE THREAD

**Issue by tianbuwandekeng** [facebookresearch/VidOSC#5]
Hi，Good job！！
Could you provide the unlabeled train annotations files of Changeit dataset？
Thanks a lot！！

**Comment by zihuixue** [comment]
Hi @tianbuwandekeng,

Please see the training files for ChangeIt [here](https://drive.google.com/drive/folders/1z9RQIp4X1lmRSRDZ93oHGoBCKw_hZGpA?usp=sharing). Let me know if there is any further question!
