### ISSUE TITLE
Code of ChangeIt  and ChangeIt (open-world)

### ISSUE THREAD

**Issue by 2557735254** [facebookresearch/VidOSC#6]
Hi, I have viewed your paper and found your network framework is highly inspired for me!!!
I'm trying to replicate your experiments on ChangeIt dataset  and ChangeIt (open-world) dataset,but I encountered difficulties while building the annotations files.May I request your code and annotations files of ChangeIt dataset  and ChangeIt (open-world) dataset?
It would be very helpful for me to strengthen my understanding of your great work!!
Anyway, gratitude for your great work!!!!

**Comment by zihuixue** [comment]
Hi @2557735254

Thank you for your interest in our work. We are glad to hear that you find VidOSC inspiring.

We have updated the repository to include the code for ChangeIt and ChangeIt (open-world), with all necessary files (checkpoints, CLIP pseudo labels) needed to reproduce the experiments. 

Please feel free to reach out if you have any further questions or run into any issues.
