### ISSUE TITLE
Changeit Code

### ISSUE THREAD

**Issue by 14-kh** [facebookresearch/VidOSC#7]
Hi!!Could you release the code of changeit dataset?

**Comment by zihuixue** [comment]
Hi @14-kh 

Thank you for your interest in our work. We have updated the repository to include the code for ChangeIt and ChangeIt (open-world), with all necessary files (checkpoints, CLIP pseudo labels) needed to reproduce the experiments. 

Please feel free to reach out if you have any further questions or run into any issues.
