### ISSUE TITLE
The results of changeit dataset

### ISSUE THREAD

**Issue by ZhichaoWang6** [facebookresearch/VidOSC#9]
I cannot reproduce 57% 84% of the metrics on the changeit dataset.
The results I got are model-epoch=05-val_avg_prec_1=0.4230val_avg_action_prec_1=0.6487.
And the model indicators gradually decrease after the fifth round.
Is there anything wrong with my settings?

My model setting parameters are as follows：
```
args ={
    "dataset_root": "/data/wzc/data/changeit",
    "ignore_video_weight": false,
    "category": null,
    "novel_obj": false,
    "bg_thre": 0.5,
    "state_thre1": 0.35,
    "state_thre2": 0.37,
    "action_thre": 0.4,
    "det": 1,
    "transformer_heads": 4,
    "transformer_layers": 3,
    "transformer_dim": 512,
    "transformer_dropout": 0.1,
    "gpus": 1,
    "lr": 0.0001,
    "wd": 0.0001,
    "batch_size": 64,
    "num_workers": 8,
    "n_epochs": 50,
    "log_dir": "./logs",
    "log_name": "multi_task",
    "ckpt": "",
    "use_gt_action": true,
    "ordering": false
}
```

**Comment by zihuixue** [comment]
Hi @Wangzc-kimo,

the 57% and 84% results are from the single-task versions. The multi-task version shows lower performance, as indicated in Table 7 of the paper. If you use the provided [single-task checkpoints](https://drive.google.com/drive/folders/17gbryHheM1Ch37FE1lmSLaetR4ARfw3V?usp=drive_link) and average the results across tasks, you will get the final accuracy.

Please feel free to let me know if there is any further question.
